version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:80"
    restart: always
    environment:
      - VITE_API_URL=http://localhost:8080/api
    networks:
      - api-network
  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "http"
      - "frontend_app:5173"
    environment:
      - NGROK_AUTHTOKEN=3JSJHlysscubiSSZE3VvDDuwmGw_3Axt2eGvdnj8wh2Gmdrtd
    ports:
      - "4040:4040"
    networks:
      - api-network

networks:
  api-network:
    name: api-network
    driver: bridge
    external: true