version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "5173:80"
    restart: always
    environment:
      # Use caminho relativo se o Nginx estiver configurado como Proxy, 
      # ou a URL HTTPS do ngrok do backend se forem túneis separados.
      - VITE_API_URL=/api
    networks:
      - api-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    command:
      - "http"
      - "frontend_app:80" # Corrigido para a porta interna 80
    environment:
      - NGROK_AUTHTOKEN=3JSJHlysscubiSSZE3VvDDuwmGw_3Axt2eGvdnj8wh2Gmdrtd
    ports:
      - "4040:4040"
    networks:
      - api-network

networks:
  api-network:
    name: api-network
    driver: bridge
    external: true