import React from 'react';

export const getStyles = (isMobile: boolean) => ({
  header: {
    backgroundColor: 'var(--header-bg, #1d4ed8)',
    color: 'var(--text-on-header, #ffffff)',
    padding: isMobile ? '0.5rem 0.75rem' : '0.75rem 1.5rem',
    display: 'flex',
    flexDirection: isMobile ? ('column' as const) : ('row' as const),
    alignItems: isMobile ? 'stretch' : 'center',
    justifyContent: 'space-between',
    gap: isMobile ? '0.4rem' : '1.5rem',
    position: 'relative' as const,
    zIndex: 40,
    width: '100%',
    boxSizing: 'border-box' as const,
  },

  topBarMobile: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },

  logoGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  logoBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: isMobile ? '0.2rem 0.45rem' : '0.4rem 0.75rem',
    borderRadius: '0.375rem',
    fontWeight: 900,
    fontSize: isMobile ? '0.75rem' : '1.1rem',
    letterSpacing: '0.03em',
    color: 'var(--text-on-header, #ffffff)',
  },
  titleGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  mainTitle: {
    margin: 0,
    fontWeight: 'bold',
    fontSize: isMobile ? '0.85rem' : '1.15rem',
    lineHeight: '1.2',
    color: 'var(--text-on-header, #ffffff)',
  },
  subtitle: {
    display: isMobile ? 'none' : 'block',
    margin: 0,
    fontSize: '0.75rem',
    color: 'rgba(255, 255, 255, 0.8)',
  },

  controlsGroup: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: isMobile ? 'space-between' : 'flex-end',
    gap: isMobile ? '0.35rem' : '1rem',
    width: isMobile ? '100%' : 'auto',
  },
  dropdownContainer: {
    position: 'relative' as const,
    display: 'inline-block',
  },
  themeTriggerBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    border: 'none',
    borderRadius: '999px',
    color: 'var(--text-on-header, #ffffff)',
    padding: isMobile ? '0.35rem 0.6rem' : '0.5rem 0.9rem',
    fontSize: isMobile ? '0.75rem' : '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  getStudentViewBtn: (isStudentView: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    backgroundColor: isStudentView ? '#F59E0B' : 'rgba(255, 255, 255, 0.1)',
    borderColor: isStudentView ? '#F59E0B' : 'rgba(255, 255, 255, 0.3)',
    borderStyle: 'solid',
    borderWidth: '1px',
    borderRadius: '999px',
    color: 'var(--text-on-header, #ffffff)',
    padding: isMobile ? '0.35rem 0.6rem' : '0.5rem 0.9rem',
    fontSize: isMobile ? '0.75rem' : '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  }),

  profileTriggerContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    cursor: 'pointer',
  },
  profileTextContainer: {
    display: isMobile ? 'none' : 'block',
    textAlign: 'right' as const,
  },
  profileName: {
    margin: 0,
    fontWeight: 'bold',
    fontSize: '0.85rem',
    lineHeight: '1.1',
    color: 'var(--text-on-header, #ffffff)',
  },
  profileRoleText: {
    margin: 0,
    fontSize: '0.7rem',
    color: 'rgba(255, 255, 255, 0.8)',
  },
  profileAvatarWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.2rem',
  },
  headerAvatarImg: {
    width: isMobile ? '1.8rem' : '2.2rem',
    height: isMobile ? '1.8rem' : '2.2rem',
    borderRadius: '50%',
    objectFit: 'cover' as const,
    border: '1.5px solid rgba(255, 255, 255, 0.8)',
  },
  headerAvatarFallback: (bgColor?: string): React.CSSProperties => ({
    width: isMobile ? '1.8rem' : '2.2rem',
    height: isMobile ? '1.8rem' : '2.2rem',
    borderRadius: '50%',
    backgroundColor: bgColor || 'rgba(255, 255, 255, 0.2)',
    color: '#FFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: isMobile ? '0.75rem' : '0.85rem',
    fontWeight: 'bold',
    border: '1.5px solid rgba(255, 255, 255, 0.8)',
  }),

  themeMenuDropdown: {
    position: 'absolute' as const,
    top: 'calc(100% + 0.5rem)',
    left: isMobile ? 0 : 'auto',
    right: isMobile ? 'auto' : 0,
    backgroundColor: 'var(--bg-surface, #ffffff)',
    border: '1px solid var(--border-color, #e5e7eb)',
    borderRadius: '0.5rem',
    width: '200px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.2)',
    color: 'var(--text-primary, #1f2937)',
    zIndex: 100,
    overflow: 'hidden',
  },
  profileDropdownMenu: {
    position: 'absolute' as const,
    top: 'calc(100% + 0.5rem)',
    right: 0,
    backgroundColor: 'var(--bg-surface, #ffffff)',
    border: '1px solid var(--border-color, #e5e7eb)',
    borderRadius: '0.5rem',
    width: '220px',
    boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.2)',
    color: 'var(--text-primary, #1f2937)',
    zIndex: 100,
    overflow: 'hidden',
  },
  menuHeader: {
    padding: '0.6rem 0.8rem',
    borderBottom: '1px solid var(--border-color, #e5e7eb)',
  },
  menuHeaderTitle: {
    fontSize: '0.75rem',
    fontWeight: 'bold',
    color: 'var(--text-secondary, #6b7280)',
  },
  themeOptionList: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  getThemeOptionBtn: (isSelected: boolean): React.CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 0.8rem',
    backgroundColor: isSelected ? 'var(--dropdown-hover, #f3f4f6)' : 'transparent',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
  }),
  themeDotsGroup: {
    display: 'flex',
    gap: '0.15rem',
    width: '1.2rem',
  },
  themeDot: (color: string): React.CSSProperties => ({
    width: '0.45rem',
    height: '0.45rem',
    borderRadius: '50%',
    backgroundColor: color,
  }),
  themeIconSpan: {
    fontSize: '0.85rem',
  },
  getThemeNameSpan: (isSelected: boolean): React.CSSProperties => ({
    fontSize: '0.8rem',
    fontWeight: isSelected ? 'bold' : 'normal',
    flex: 1,
    color: 'var(--text-primary, #1f2937)',
    textAlign: 'left' as const,
  }),
  profileInfoSection: {
    padding: '0.75rem',
    display: 'flex',
    gap: '0.5rem',
    alignItems: 'center',
    borderBottom: '1px solid var(--border-color, #e5e7eb)',
  },
  dropdownAvatarImg: {
    width: '2.2rem',
    height: '2.2rem',
    borderRadius: '50%',
    objectFit: 'cover' as const,
  },
  dropdownAvatarFallback: (bgColor?: string): React.CSSProperties => ({
    width: '2.2rem',
    height: '2.2rem',
    borderRadius: '50%',
    backgroundColor: bgColor || 'var(--bg-surface, #e5e7eb)',
    color: '#FFF',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.85rem',
    fontWeight: 'bold',
  }),
  profileDetailsBox: {
    overflow: 'hidden',
    textAlign: 'left' as const,
  },
  profileDetailName: {
    margin: 0,
    fontWeight: 'bold',
    fontSize: '0.8rem',
    color: 'var(--text-primary, #1f2937)',
  },
  profileDetailEmail: {
    margin: '0.1rem 0',
    fontSize: '0.7rem',
    color: 'var(--text-secondary, #6b7280)',
  },
  getRoleBadge: (isAdmin: boolean): React.CSSProperties => ({
    display: 'inline-block',
    backgroundColor: isAdmin ? 'rgba(239, 68, 68, 0.15)' : 'rgba(59, 130, 246, 0.15)',
    color: isAdmin ? '#EF4444' : '#3B82F6',
    fontSize: '0.65rem',
    padding: '0.1rem 0.3rem',
    borderRadius: '0.2rem',
    fontWeight: 600,
  }),
  profileActionsSection: {
    padding: '0.35rem',
  },
  actionBtn: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.4rem 0.6rem',
    background: 'transparent',
    border: 'none',
    color: 'var(--text-primary, #1f2937)',
    cursor: 'pointer',
    borderRadius: '0.25rem',
    textAlign: 'left' as const,
  },
  actionTitle: {
    fontWeight: 600,
    fontSize: '0.8rem',
  },
  actionSubtitle: {
    fontSize: '0.65rem',
    color: 'var(--text-secondary, #6b7280)',
  },
  logoutBtn: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.4rem 0.6rem',
    background: 'transparent',
    border: 'none',
    color: '#EF4444',
    cursor: 'pointer',
    borderRadius: '0.25rem',
    textAlign: 'left' as const,
  },
  logoutText: {
    fontWeight: 600,
    fontSize: '0.8rem',
  },
});