import React from 'react';

export const styles = {
  pageContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    backgroundColor: 'var(--bg-main)',
    minHeight: '100vh',
    width: '100%',
    maxWidth: '100vw',
    overflowX: 'hidden' as const,
  },
  contentContainer: {
    padding: '1.5rem 1rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1.5rem',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  headerTitle: {
    margin: '0 0 0.5rem 0',
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: 'var(--text-secondary)',
  },
  headerSubtitle: {
    margin: 0,
    color: 'var(--text-secondary)',
    fontSize: '0.875rem',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '1rem',
    width: '100%',
  },
  totalSpentCard: {
    background: 'var(--header-bg)',
    color: 'var(--text-on-header)',
    padding: '1.25rem',
    borderRadius: '0.75rem',
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  cardLabel: {
    fontSize: '0.75rem',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  cardValue: {
    margin: '0.75rem 0 0 0',
    fontSize: '1.75rem',
    fontWeight: 'bold',
  },
  cardIconWrapper: {
    position: 'absolute' as const,
    top: '1.25rem',
    right: '1.25rem',
    background: 'var(--primary-color)',
    padding: '0.5rem',
    borderRadius: '0.375rem',
  },
  surfaceCard: {
    background: 'var(--bg-surface)',
    padding: '1.25rem',
    borderRadius: '0.75rem',
    border: '1px solid var(--border-color)',
    display: 'flex',
    flexDirection: 'column' as const,
    position: 'relative' as const,
  },
  surfaceCardLabel: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  surfaceCardValue: {
    margin: '0.75rem 0 0 0',
    fontSize: '1.75rem',
    fontWeight: 'bold',
    color: 'var(--text-secondary)',
  },
  surfaceCardIconWrapper: {
    position: 'absolute' as const,
    top: '1.25rem',
    right: '1.25rem',
    background: 'var(--primary-color)',
    padding: '0.5rem',
    borderRadius: '0.375rem',
    color: 'var(--text-primary)',
  },
  filtersRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '1rem',
    flexWrap: 'wrap' as const,
  },
  filtersGroup: {
    display: 'flex',
    gap: '0.75rem',
    flexWrap: 'wrap' as const,
    width: '100%',
    maxWidth: '100%',
  },
  searchInputWrapper: {
    display: 'flex',
    position: 'relative' as const,
    flex: 1,
    minWidth: '200px',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '0.75rem',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#64748B',
  },
  searchInput: {
    width: '100%',
    padding: '0.625rem 0.625rem 0.625rem 2.25rem',
    borderRadius: '0.5rem',
    border: '1px solid var(--border-color)',
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-secondary)',
    outline: 'none',
    fontSize: '0.875rem',
    boxSizing: 'border-box' as const,
  },
  categorySelect: {
    padding: '0.625rem 1rem',
    borderRadius: '0.5rem',
    border: '1px solid var(--border-color)',
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: '0.875rem',
    outline: 'none',
    width: '100%',
  },
  chartBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.625rem 1rem',
    borderRadius: '0.5rem',
    border: '1px solid var(--border-color)',
    backgroundColor: 'var(--bg-surface)',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontWeight: 500,
    fontSize: '0.875rem',
    flex: 1,
  },
  newExpenseBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    padding: '0.625rem 1.25rem',
    borderRadius: '0.5rem',
    border: 'none',
    backgroundColor: 'var(--header-bg)',
    color: 'var(--text-on-header)',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '0.875rem',
    flex: 1,
  },
  tableWrapper: {
    background: 'var(--bg-surface)',
    borderRadius: '0.75rem',
    border: '1px solid var(--border-color)',
    overflowX: 'auto' as const, 
    width: '100%',
    maxWidth: '100%',
    WebkitOverflowScrolling: 'touch' as const, 
  },
  table: {
    width: '100%',
    minWidth: '600px',
    borderCollapse: 'collapse' as const,
    textAlign: 'left' as const,
    fontSize: '0.875rem',
  },
  tableHeaderRow: {
    borderBottom: '1px solid var(--border-color)',
    color: 'var(--text-secondary)',
    fontSize: '0.75rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  thCell: {
    padding: '1rem',
    fontWeight: 600,
  },
  thCellRight: {
    padding: '1rem',
    textAlign: 'right' as const,
    fontWeight: 600,
  },
  thCellCenter: {
    padding: '1rem',
    textAlign: 'center' as const,
    fontWeight: 600,
  },
  tableRow: {
    borderBottom: '1px solid var(--border-color)',
  },
  tdDate: {
    padding: '1rem',
    color: 'var(--text-secondary)',
    whiteSpace: 'nowrap' as const,
  },
  tdDesc: {
    padding: '1rem',
    fontWeight: 500,
    color: 'var(--text-primary)',
  },
  tdCategory: {
    padding: '1rem',
  },
  getBadgeStyle: (bg: string, text: string): React.CSSProperties => ({
    backgroundColor: bg,
    color: text,
    padding: '0.25rem 0.75rem',
    borderRadius: '999px',
    fontSize: '0.75rem',
    fontWeight: 700,
    whiteSpace: 'nowrap',
  }),
  tdAmount: {
    padding: '1rem',
    textAlign: 'right' as const,
    fontWeight: 'bold',
    color: 'var(--text-primary)',
    fontFamily: 'monospace',
    fontSize: '0.9rem',
  },
  tdActions: {
    padding: '1rem',
    textAlign: 'center' as const,
  },
  actionsGroup: {
    display: 'flex',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  actionIconButton: {
    background: 'transparent',
    border: 'none',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    padding: '0.25rem',
  },
  emptyTableMessage: {
    padding: '2rem',
    textAlign: 'center' as const,
    color: 'var(--text-secondary)',
  },
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: '1rem',
  },
  modalBox: {
    background: 'var(--bg-surface)',
    borderRadius: '0.75rem',
    padding: '1.5rem',
    width: '100%',
    maxWidth: '450px',
    border: '1px solid var(--border-color)',
    boxSizing: 'border-box' as const,
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.25rem',
  },
  modalTitle: {
    margin: 0,
    fontSize: '1.25rem',
    color: 'var(--text-secondary)',
  },
  modalCloseBtn: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  fieldLabel: {
    display: 'block',
    fontSize: '0.8rem',
    fontWeight: 600,
    color: 'var(--text-secondary)',
    marginBottom: '0.375rem',
  },
  fieldInput: {
    width: '100%',
    padding: '0.625rem',
    borderRadius: '0.375rem',
    border: '1px solid var(--border-color)',
    background: 'var(--bg-main)',
    color: 'var(--text-secondary)',
    boxSizing: 'border-box' as const,
    fontSize: '0.875rem',
  },
  formSubmitBtn: {
    marginTop: '0.5rem',
    padding: '0.75rem',
    background: 'var(--header-bg)',
    color: 'var(--text-primary)',
    border: 'none',
    borderRadius: '0.375rem',
    fontWeight: 'bold',
    cursor: 'pointer',
    width: '100%',
    fontSize: '0.9rem',
  },
};