export const getStyles = (isMobile: boolean) => ({
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.65)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: isMobile ? 'flex-end' : 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: isMobile ? 0 : '16px',
  },
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: isMobile ? '16px 16px 0 0' : '12px',
    width: '100%',
    maxWidth: isMobile ? '100%' : '540px',
    maxHeight: isMobile ? '92vh' : '85vh',
    display: 'flex',
    flexDirection: 'column' as const,
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: isMobile ? '14px 16px' : '16px 20px',
    borderBottom: '1px solid #f3f4f6',
    backgroundColor: '#fffbeb', // Ocre suave
  },
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 600,
    fontSize: isMobile ? '15px' : '16px',
    color: '#78350f', // Ocre escuro
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#92400e',
    padding: '6px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    padding: isMobile ? '16px' : '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '18px',
    overflowY: 'auto' as const,
    maxHeight: isMobile ? 'calc(92vh - 60px)' : 'calc(85vh - 60px)',
  },
  section: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#92400e',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  viewerBox: {
    backgroundColor: '#fafaf9',
    border: '1px solid #e7e5e4',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    justifyContent: 'center',
  },
  emptyReceipt: {
    padding: isMobile ? '20px 12px' : '28px 16px',
    textAlign: 'center' as const,
    backgroundColor: '#fffbeb',
    border: '1px dashed #fcd34d',
    borderRadius: '8px',
    color: '#b45309',
    fontSize: '13px',
  },
  pdfCard: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '12px',
    padding: '16px',
  },
  downloadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#d97706', // Ocre principal
    color: '#ffffff',
    padding: '8px 16px',
    borderRadius: '6px',
    textDecoration: 'none',
    fontSize: '13px',
    fontWeight: 600,
  },
  imagePreviewContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '8px',
    width: '100%',
  },
  imagePreview: {
    maxWidth: '100%',
    maxHeight: isMobile ? '40vh' : '50vh',
    borderRadius: '6px',
    objectFit: 'contain' as const,
  },
  openExternalLink: {
    fontSize: '12px',
    color: '#d97706',
    fontWeight: 600,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  uploadSection: {
    borderTop: '1px solid #f3f4f6',
    paddingTop: '16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  uploadForm: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  dropZone: {
    border: '2px dashed #fcd34d',
    borderRadius: '8px',
    padding: isMobile ? '16px' : '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    backgroundColor: '#fffbeb',
  },
  dropText: {
    fontSize: '13px',
    color: '#78350f',
    textAlign: 'center' as const,
    fontWeight: 500,
  },
  localPreviewBox: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  previewLabel: {
    fontSize: '12px',
    color: '#78350f',
    fontWeight: 500,
  },
  localPreviewImage: {
    maxHeight: '20vh',
    borderRadius: '6px',
    objectFit: 'contain' as const,
  },
  submitBtn: (disabled: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    backgroundColor: disabled ? '#fcd34d' : '#d97706',
    color: '#ffffff',
    border: 'none',
    padding: '11px',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: 600,
    cursor: disabled ? 'not-allowed' : 'pointer',
  }),
  alertError: {
    backgroundColor: '#fef2f2',
    color: '#991b1b',
    padding: '10px 16px',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid #fecaca',
  },
  alertSuccess: {
    backgroundColor: '#f0fdf4',
    color: '#166534',
    padding: '10px 16px',
    fontSize: '13px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid #bbf7d0',
  },
})