export const getStyles = (isMobile: boolean) => ({
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: isMobile ? 'flex-end' : 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: isMobile ? 0 : '16px',
  },
  modal: {
    backgroundColor: 'var(--bg-surface)',
    border: '1px solid var(--border-color)',
    borderRadius: isMobile ? '16px 16px 0 0' : '12px',
    width: '100%',
    maxWidth: isMobile ? '100%' : '540px',
    maxHeight: isMobile ? '92vh' : '85vh',
    display: 'flex',
    flexDirection: 'column' as const,
    boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.35)',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: isMobile ? '14px 16px' : '16px 20px',
    borderBottom: '1px solid var(--border-color)',
    backgroundColor: 'var(--dropdown-hover)',
  },
  headerTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: 900,
    fontSize: isMobile ? '15px' : '16px',
    color: 'var(--text-primary)',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: 'var(--text-secondary)',
    padding: '6px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  body: {
    padding: isMobile ? '16px' : '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '18px',
    overflowY: 'auto' as const,
    maxHeight: isMobile ? 'calc(92vh - 60px)' : 'calc(85vh - 60px)',
    backgroundColor: 'var(--bg-surface)',
  },
  section: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  sectionTitle: {
    fontSize: '12px',
    fontWeight: 900,
    color: 'var(--primary-color)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.05em',
  },
  viewerBox: {
    backgroundColor: 'var(--bg-main)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    padding: '12px',
    display: 'flex',
    justifyContent: 'center',
  },
  emptyReceipt: {
    padding: isMobile ? '20px 12px' : '28px 16px',
    textAlign: 'center' as const,
    backgroundColor: 'var(--dropdown-hover)',
    border: '1px dashed var(--border-color)',
    borderRadius: '8px',
    color: 'var(--text-secondary)',
    fontSize: '13px',
    fontWeight: 700,
  },
  pdfCard: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '12px',
    padding: '16px',
    color: 'var(--text-primary)',
  },
  downloadBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'var(--primary-color)',
    color: 'var(--text-on-header)',
    padding: '8px 16px',
    borderRadius: '6px',
    textDecoration: 'none',
    fontSize: '13px',
    fontWeight: 900,
  },
  imagePreviewContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '8px',
    width: '100%',
  },
  imagePreview: {
    maxWidth: '100%',
    maxHeight: isMobile ? '40vh' : '50vh',
    borderRadius: '6px',
    objectFit: 'contain' as const,
  },
  openExternalLink: {
    fontSize: '12px',
    color: 'var(--primary-color)',
    fontWeight: 900,
    textDecoration: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  uploadSection: {
    borderTop: '1px solid var(--border-color)',
    paddingTop: '16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  uploadForm: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  dropZone: {
    border: '2px dashed var(--border-color)',
    borderRadius: '8px',
    padding: isMobile ? '16px' : '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '8px',
    cursor: 'pointer',
    backgroundColor: 'var(--input-bg)',
  },
  dropText: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    textAlign: 'center' as const,
    fontWeight: 700,
  },
  localPreviewBox: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  previewLabel: {
    fontSize: '12px',
    color: 'var(--text-secondary)',
    fontWeight: 700,
  },
  localPreviewImage: {
    maxHeight: '20vh',
    borderRadius: '6px',
    objectFit: 'contain' as const,
  },
  submitBtn: (disabled: boolean) => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    backgroundColor: disabled ? 'var(--border-color)' : 'var(--primary-color)',
    color: disabled ? 'var(--text-secondary)' : 'var(--text-on-header)',
    border: 'none',
    padding: '11px',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: 900,
    cursor: disabled ? 'not-allowed' : 'pointer',
  }),
  alertError: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    color: '#ef4444',
    padding: '10px 16px',
    fontSize: '13px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid rgba(239, 68, 68, 0.3)',
  },
  alertSuccess: {
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    color: '#22c55e',
    padding: '10px 16px',
    fontSize: '13px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid rgba(34, 197, 94, 0.3)',
  },
});