import React from 'react';

export const getStyles = (isMobile: boolean = false) => ({
  container: {
    maxWidth: '1100px',
    margin: '0 auto',
    padding: isMobile ? '16px 12px' : '24px 16px',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  headerContainer: {
    marginBottom: '24px',
  },
  title: {
    fontSize: isMobile ? '20px' : '24px',
    fontWeight: 800,
    color: 'var(--text-secondary, #1e293b)',
    margin: '0 0 4px 0',
  },
  subtitle: {
    fontSize: isMobile ? '13px' : '14px',
    color: 'var(--text-secondary, #64748b)',
    margin: 0,
  },
  errorAlert: {
    padding: '12px 16px',
    marginBottom: '20px',
    borderRadius: '8px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#991b1b',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
  },

  /* MODO CHAT */
  chatContainer: {
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderRadius: '16px',
    border: '1px solid var(--border-color, #e2e8f0)',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    overflow: 'hidden',
  },
  chatHeader: {
    padding: isMobile ? '12px 16px' : '16px 24px',
    backgroundColor: '#1e3a8a',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  chatHeaderTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  backBtn: {
    background: 'none',
    border: 'none',
    color: '#ffffff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    padding: '4px',
  },
  chatHeaderTitle: {
    fontWeight: 700,
    fontSize: isMobile ? '14px' : '15px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  chatHeaderSubtitle: {
    fontSize: '12px',
    color: '#93c5fd',
  },
  newManifestationBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    color: '#fff',
    border: 'none',
    padding: isMobile ? '6px 10px' : '6px 14px',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
  chatMessagesBox: {
    height: '420px',
    overflowY: 'auto' as const,
    padding: isMobile ? '14px' : '20px',
    backgroundColor: '#f8fafc',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  systemMsgContainer: {
    textAlign: 'center' as const,
    margin: '8px 0',
  },
  systemMsgText: {
    backgroundColor: '#e0f2fe',
    color: '#0369a1',
    fontSize: '12px',
    padding: '6px 14px',
    borderRadius: '20px',
    fontWeight: 500,
  },
  getBubbleContainer: (isUser: boolean): React.CSSProperties => ({
    display: 'flex',
    flexDirection: 'column',
    alignItems: isUser ? 'flex-end' : 'flex-start',
  }),
  getBubble: (isUser: boolean): React.CSSProperties => ({
    maxWidth: isMobile ? '85%' : '75%',
    backgroundColor: isUser ? '#2563eb' : '#ffffff',
    color: isUser ? '#ffffff' : '#1e293b',
    padding: '12px 16px',
    borderRadius: isUser ? '16px 16px 2px 16px' : '16px 16px 16px 2px',
    border: isUser ? 'none' : '1px solid #e2e8f0',
    fontSize: '14px',
    lineHeight: '1.5',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    whiteSpace: 'pre-line' as const,
    wordBreak: 'break-word' as const,
  }),
  bubbleMeta: {
    fontSize: '11px',
    color: '#94a3b8',
    marginTop: '4px',
    padding: '0 4px',
  },
  chatForm: {
    padding: '16px',
    backgroundColor: '#ffffff',
    borderTop: '1px solid #e2e8f0',
    display: 'flex',
    gap: '12px',
  },
  chatInput: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    fontSize: '14px',
    outline: 'none',
  },
  getSendBtn: (isSending: boolean): React.CSSProperties => ({
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    padding: isMobile ? '0 14px' : '0 20px',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: isSending ? 'not-allowed' : 'pointer',
    opacity: isSending ? 0.7 : 1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  }),

  /* CARD SUCESSO */
  successCard: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: isMobile ? '24px 16px' : '40px 24px',
    textAlign: 'center' as const,
    border: '1px solid #e2e8f0',
    maxWidth: '600px',
    margin: '0 auto',
  },
  successTitle: {
    fontSize: '20px',
    fontWeight: 700,
    color: '#1e293b',
    margin: '0 0 8px 0',
  },
  successText: {
    fontSize: '14px',
    color: '#64748b',
    marginBottom: '20px',
  },
  successBtn: {
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    padding: '10px 24px',
    borderRadius: '8px',
    fontWeight: 600,
    cursor: 'pointer',
  },

  /* MODO FORMULÁRIO PRINCIPAL */
  formLayout: {
    display: isMobile ? 'flex' : 'grid',
    flexDirection: isMobile ? ('column' as const) : undefined,
    gridTemplateColumns: isMobile ? undefined : '1fr 320px',
    gap: '24px',
  },
  formContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  card: {
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    padding: '18px 20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.02)',
  },
  cardAnonHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardAnonTitle: {
    fontWeight: 700,
    fontSize: '14px',
    color: 'var(--text-secondary, #1e293b)',
  },
  cardAnonDesc: {
    fontSize: '13px',
    color: 'var(--text-secondary, #64748b)',
  },
  toggleSwitch: {
    position: 'relative' as const,
    display: 'inline-block',
    width: '44px',
    height: '24px',
    cursor: 'pointer',
  },
  toggleInput: {
    opacity: 0,
    width: 0,
    height: 0,
  },
  getToggleTrack: (isAnonymous: boolean): React.CSSProperties => ({
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: isAnonymous ? '#2563eb' : '#cbd5e1',
    borderRadius: '24px',
    transition: '0.2s',
  }),
  getToggleThumb: (isAnonymous: boolean): React.CSSProperties => ({
    position: 'absolute',
    content: '""',
    height: '18px',
    width: '18px',
    left: isAnonymous ? '22px' : '3px',
    bottom: '3px',
    backgroundColor: '#ffffff',
    borderRadius: '50%',
    transition: '0.2s',
  }),
  getContactCard: (isAnonymous: boolean): React.CSSProperties => ({
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    padding: '18px 20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.02)',
    opacity: isAnonymous ? 0.6 : 1,
    transition: 'opacity 0.2s',
  }),
  contactGrid: {
    display: isMobile ? 'flex' : 'grid',
    flexDirection: isMobile ? ('column' as const) : undefined,
    gridTemplateColumns: isMobile ? undefined : '1fr 1fr',
    gap: '12px',
  },
  sectionHeader: {
    fontWeight: 700,
    fontSize: '12px',
    color: 'var(--text-secondary, #475569)',
    letterSpacing: '0.5px',
    marginBottom: '14px',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 600,
    color: 'var(--text-secondary, #475569)',
    marginBottom: '6px',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: '8px',
    border: '1px solid var(--border-color, #cbd5e1)',
    backgroundColor: 'var(--bg-main, #ffffff)',
    fontSize: '14px',
    color: 'var(--text-secondary, #1e293b)',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  fieldCounter: {
    textAlign: 'right' as const,
    fontSize: '12px',
    color: 'var(--text-secondary, #64748b)',
    marginTop: '4px',
  },
  getSubmitBtn: (isSubmitting: boolean): React.CSSProperties => ({
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    padding: '14px',
    fontSize: '15px',
    fontWeight: 700,
    cursor: isSubmitting ? 'not-allowed' : 'pointer',
    opacity: isSubmitting ? 0.7 : 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    boxShadow: '0 4px 6px -1px rgba(37, 99, 235, 0.2)',
  }),

  /* SIDEBAR */
  sidebar: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  sidebarTitle: {
    fontWeight: 700,
    fontSize: '12px',
    color: 'var(--text-secondary, #475569)',
    letterSpacing: '0.5px',
    marginBottom: '16px',
  },
  stepList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
    color: 'var(--text-secondary, #475569)',
  },
  stepItemContainer: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
  },
  stepBadge: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: '#1e3a8a',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: 700,
    flexShrink: 0,
  },
  stepTitle: {
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--text-secondary, #1e293b)',
  },
  stepDescription: {
    fontSize: '12px',
    color: 'var(--text-secondary, #64748b)',
    marginTop: '2px',
    lineHeight: '1.3',
  },
  infoBox: {
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderRadius: '12px',
    padding: '16px',
    border: '1px solid var(--border-color, #e2e8f0)',
    display: 'flex',
    gap: '10px',
    fontSize: '13px',
    color: 'var(--text-secondary, #475569)',
    lineHeight: '1.4',
  },
});