import React from 'react';

export const getStyles = (isMobile: boolean, isDetailOpenMobile: boolean) => ({
  container: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: isMobile ? '12px' : '24px',
    color: 'var(--text-primary, #1e293b)',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  headerContainer: {
    marginBottom: isMobile ? '16px' : '24px',
  },
  title: {
    fontSize: isMobile ? '20px' : '24px',
    color: 'var(--text-primary, #1e293b)',
    margin: '0 0 4px 0',
    fontWeight: 700,
  },
  subtitle: {
    fontSize: isMobile ? '12px' : '14px',
    color: 'var(--text-secondary, #475569)',
    margin: 0,
    opacity: 0.85,
  },
  errorAlert: {
    padding: '12px 16px',
    marginBottom: '16px',
    borderRadius: '8px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#991b1b',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: isMobile ? '12px' : '14px',
  },
  retryBtn: {
    marginLeft: 'auto',
    background: 'none',
    border: 'none',
    color: '#991b1b',
    textDecoration: 'underline',
    cursor: 'pointer',
    fontSize: isMobile ? '12px' : '14px',
  },
  gridContainer: {
    display: isMobile ? 'flex' : 'grid',
    flexDirection: isMobile ? ('column' as const) : undefined,
    gridTemplateColumns: isMobile ? undefined : '380px 1fr',
    gap: isMobile ? '12px' : '20px',
    height: isMobile ? 'calc(100vh - 160px)' : 'calc(100vh - 180px)',
  },

  /* COLUNA DA ESQUERDA: LISTA */
  listColumn: {
    display: isMobile && isDetailOpenMobile ? 'none' : 'flex',
    flexDirection: 'column' as const,
    backgroundColor: 'var(--bg-surface, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    overflow: 'hidden',
    height: '100%',
  },
  searchHeader: {
    padding: isMobile ? '12px' : '16px',
    borderBottom: '1px solid var(--border-color, #e2e8f0)',
    backgroundColor: 'var(--bg-main, #f8fafc)',
  },
  searchBox: {
    position: 'relative' as const,
    marginBottom: '10px',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '12px',
    top: '10px',
    color: 'var(--text-secondary, #64748b)',
    opacity: 0.5,
  },
  searchInput: {
    width: '100%',
    padding: '8px 12px 8px 36px',
    borderRadius: '8px',
    border: '1px solid var(--border-color, #e2e8f0)',
    backgroundColor: 'var(--input-bg, #ffffff)',
    color: 'var(--text-primary, #1e293b)',
    fontSize: '13px',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  filterGroup: {
    display: 'flex',
    gap: '6px',
    overflowX: 'auto' as const,
    paddingBottom: isMobile ? '4px' : '0',
  },
  getFilterBtn: (isActive: boolean): React.CSSProperties => ({
    border: 'none',
    padding: '4px 10px',
    borderRadius: '6px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    backgroundColor: isActive ? 'var(--primary-color, #2563eb)' : 'var(--dropdown-hover, #f1f5f9)',
    color: isActive ? '#ffffff' : 'var(--text-secondary, #475569)',
    transition: 'all 0.15s ease',
    whiteSpace: 'nowrap' as const,
  }),
  listContent: {
    flex: 1,
    overflowY: 'auto' as const,
  },
  loaderBox: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    color: 'var(--text-secondary, #64748b)',
  },
  emptyBox: {
    padding: '24px',
    textAlign: 'center' as const,
    color: 'var(--text-secondary, #64748b)',
    opacity: 0.6,
    fontSize: '13px',
  },
  getListItem: (isSelected: boolean): React.CSSProperties => ({
    padding: '14px 16px',
    borderBottom: '1px solid var(--border-color, #e2e8f0)',
    backgroundColor: isSelected ? 'var(--dropdown-hover, #f1f5f9)' : 'var(--bg-surface, #ffffff)',
    borderLeft: isSelected ? '4px solid var(--primary-color, #2563eb)' : '4px solid transparent',
    cursor: 'pointer',
    transition: 'background 0.15s',
  }),
  itemTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '4px',
  },
  itemProtocol: {
    fontSize: '12px',
    color: 'var(--primary-color, #2563eb)',
    fontWeight: 600,
  },
  getStatusBadge: (status: string): React.CSSProperties => {
    let bg = '#fef3c7';
    let color = '#b45309';
    if (status === 'EM_ANDAMENTO') {
      bg = '#dbeafe';
      color = '#1d4ed8';
    } else if (status === 'CONCLUIDO') {
      bg = '#dcfce7';
      color = '#15803d';
    }
    return {
      fontSize: '10px',
      padding: '2px 8px',
      borderRadius: '10px',
      backgroundColor: bg,
      color: color,
      fontWeight: 600,
    };
  },
  itemTitle: {
    fontSize: '13px',
    color: 'var(--text-primary, #1e293b)',
    fontWeight: 500,
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  itemFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
    color: 'var(--text-secondary, #64748b)',
    opacity: 0.8,
    marginTop: '6px',
  },

  /* COLUNA DA DIREITA: DETALHES E CHAT */
  chatColumn: {
    display: isMobile && !isDetailOpenMobile ? 'none' : 'flex',
    flexDirection: 'column' as const,
    backgroundColor: 'var(--bg-surface, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    overflow: 'hidden',
    height: '100%',
  },
  chatHeader: {
    padding: isMobile ? '12px 16px' : '16px 24px',
    borderBottom: '1px solid var(--border-color, #e2e8f0)',
    backgroundColor: 'var(--bg-surface, #ffffff)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '12px',
  },
  chatTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flex: 1,
    overflow: 'hidden',
  },
  backBtnMobile: {
    display: isMobile ? 'flex' : 'none',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'none',
    border: 'none',
    color: 'var(--primary-color, #2563eb)',
    cursor: 'pointer',
    padding: '4px',
  },
  chatTitle: {
    fontSize: isMobile ? '15px' : '18px',
    fontWeight: 600,
    color: 'var(--text-primary, #1e293b)',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  chatMeta: {
    fontSize: '12px',
    color: 'var(--text-secondary, #64748b)',
    marginTop: '2px',
  },
  statusSelectBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  statusLabel: {
    fontSize: '12px',
    color: 'var(--text-secondary, #64748b)',
    display: isMobile ? 'none' : 'inline',
  },
  statusSelect: {
    padding: '6px 10px',
    borderRadius: '6px',
    border: '1px solid var(--border-color, #e2e8f0)',
    backgroundColor: 'var(--input-bg, #ffffff)',
    color: 'var(--text-primary, #1e293b)',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  applicantBar: {
    padding: '10px 16px',
    backgroundColor: 'var(--bg-main, #f8fafc)',
    borderBottom: '1px solid var(--border-color, #e2e8f0)',
    fontSize: '12px',
    color: 'var(--text-secondary, #475569)',
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: isMobile ? '10px' : '20px',
  },
  messageList: {
    flex: 1,
    padding: isMobile ? '12px' : '20px',
    backgroundColor: 'var(--bg-main, #f8fafc)',
    overflowY: 'auto' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  systemMsgWrapper: {
    textAlign: 'center' as const,
    margin: '4px 0',
  },
  systemMsgSpan: {
    backgroundColor: 'var(--dropdown-hover, #e2e8f0)',
    color: 'var(--text-secondary, #475569)',
    fontSize: '11px',
    padding: '4px 12px',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #cbd5e1)',
  },
  getBubbleContainer: (isAdmin: boolean): React.CSSProperties => ({
    display: 'flex',
    flexDirection: 'column',
    alignItems: isAdmin ? 'flex-end' : 'flex-start',
  }),
  getBubble: (isAdmin: boolean): React.CSSProperties => ({
    maxWidth: isMobile ? '85%' : '70%',
    backgroundColor: isAdmin ? 'var(--primary-color, #2563eb)' : 'var(--bg-surface, #ffffff)',
    color: isAdmin ? '#ffffff' : 'var(--text-primary, #1e293b)',
    padding: '10px 14px',
    borderRadius: isAdmin ? '14px 14px 2px 14px' : '14px 14px 14px 2px',
    border: isAdmin ? 'none' : '1px solid var(--border-color, #e2e8f0)',
    fontSize: '13px',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
    whiteSpace: 'pre-line' as const,
    wordBreak: 'break-word' as const,
  }),
  bubbleMeta: {
    fontSize: '11px',
    color: 'var(--text-secondary, #64748b)',
    opacity: 0.8,
    marginTop: '4px',
  },
  inputForm: {
    padding: isMobile ? '12px' : '16px',
    backgroundColor: 'var(--bg-surface, #ffffff)',
    borderTop: '1px solid var(--border-color, #e2e8f0)',
    display: 'flex',
    gap: '8px',
  },
  inputField: {
    flex: 1,
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1px solid var(--border-color, #e2e8f0)',
    backgroundColor: 'var(--input-bg, #ffffff)',
    color: 'var(--text-primary, #1e293b)',
    fontSize: '13px',
    outline: 'none',
  },
  submitBtn: (isSending: boolean): React.CSSProperties => ({
    backgroundColor: 'var(--primary-color, #2563eb)',
    color: '#ffffff',
    border: 'none',
    padding: isMobile ? '0 14px' : '0 20px',
    borderRadius: '8px',
    cursor: isSending ? 'not-allowed' : 'pointer',
    opacity: isSending ? 0.7 : 1,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontWeight: 600,
    fontSize: '13px',
    transition: 'opacity 0.15s ease',
    whiteSpace: 'nowrap' as const,
  }),
  noSelectionBox: {
    display: isMobile && !isDetailOpenMobile ? 'none' : 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--text-secondary, #64748b)',
    opacity: 0.6,
    backgroundColor: 'var(--bg-surface, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    height: '100%',
    fontSize: '14px',
  },
});