import React from 'react';

export const getStyles = (isMobile: boolean = false) => ({
  container: {
    maxWidth: '1100px',
    margin: '0 auto',
    padding: isMobile ? '16px 12px' : '24px 16px',
    fontFamily: 'system-ui, -apple-system, sans-serif',
  },
  headerContainer: {
    marginBottom: '24px',
  },
  title: {
    fontSize: isMobile ? '20px' : '24px',
    fontWeight: 800,
    color: 'var(--text-secondary, #1e293b)',
    margin: '0 0 4px 0',
  },
  subtitle: {
    fontSize: isMobile ? '13px' : '14px',
    color: 'var(--text-secondary, #64748b)',
    margin: 0,
  },
  errorAlert: {
    padding: '12px 16px',
    marginBottom: '20px',
    borderRadius: '8px',
    backgroundColor: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#991b1b',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
  },
  retryBtn: {
    marginLeft: 'auto',
    background: 'none',
    border: 'none',
    color: '#991b1b',
    textDecoration: 'underline',
    cursor: 'pointer',
  },

  /* DETALHE DA MANIFESTAÇÃO / CHAT */
  chatContainer: {
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    overflow: 'hidden',
  },
  chatHeader: {
    padding: isMobile ? '12px 16px' : '16px 24px',
    backgroundColor: '#1e3a8a',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '12px',
  },
  chatHeaderTitleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  backBtn: {
    background: 'none',
    border: 'none',
    color: '#ffffff',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    padding: '4px',
  },
  chatHeaderTitle: {
    fontWeight: 700,
    fontSize: isMobile ? '14px' : '15px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  chatHeaderSubtitle: {
    fontSize: '12px',
    color: '#93c5fd',
  },
  getStatusBadge: (status: string): React.CSSProperties => {
    const safeStatus = status ?? 'PENDENTE';
    const isPending = safeStatus === 'PENDENTE';
    const isInProgress = safeStatus === 'EM_ANDAMENTO';
    return {
      fontSize: '12px',
      fontWeight: 600,
      padding: '4px 12px',
      borderRadius: '12px',
      backgroundColor: isPending ? '#fef3c7' : isInProgress ? '#dbeafe' : '#dcfce7',
      color: isPending ? '#b45309' : isInProgress ? '#1d4ed8' : '#15803d',
      whiteSpace: 'nowrap',
    };
  },
  summaryBox: {
    padding: '16px 24px',
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderBottom: '1px solid var(--border-color, #e2e8f0)',
  },
  summaryTitle: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--text-primary, #1e293b)',
    marginBottom: '4px',
  },
  summaryDescription: {
    fontSize: '13px',
    color: 'var(--text-secondary, #64748b)',
    lineHeight: '1.4',
    whiteSpace: 'pre-line' as const,
  },
  chatMessagesBox: {
    height: '380px',
    overflowY: 'auto' as const,
    padding: isMobile ? '14px' : '20px',
    backgroundColor: 'var(--bg-main, #ffffff)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  emptyMessages: {
    textAlign: 'center' as const,
    color: '#64748b',
    fontSize: '13px',
    margin: 'auto',
  },
  systemMsgContainer: {
    textAlign: 'center' as const,
    margin: '4px 0',
  },
  systemMsgText: {
    backgroundColor: '#f1f5f9',
    color: '#475569',
    fontSize: '12px',
    padding: '4px 12px',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
  },
  getBubbleContainer: (isUser: boolean): React.CSSProperties => ({
    display: 'flex',
    flexDirection: 'column',
    alignItems: isUser ? 'flex-end' : 'flex-start',
  }),
  getBubble: (isUser: boolean): React.CSSProperties => ({
    maxWidth: isMobile ? '85%' : '75%',
    backgroundColor: isUser ? '#2563eb' : '#f1f5f9',
    color: isUser ? '#ffffff' : '#1e293b',
    padding: '12px 16px',
    borderRadius: isUser ? '16px 16px 2px 16px' : '16px 16px 16px 2px',
    fontSize: '14px',
    lineHeight: '1.5',
    whiteSpace: 'pre-line' as const,
    wordBreak: 'break-word' as const,
  }),
  bubbleMeta: {
    fontSize: '11px',
    color: '#94a3b8',
    marginTop: '4px',
  },
  chatForm: {
    padding: '16px',
    backgroundColor: '#f8fafc',
    borderTop: '1px solid #e2e8f0',
    display: 'flex',
    gap: '12px',
  },
  chatInput: {
    flex: 1,
    padding: '12px 16px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    fontSize: '14px',
    outline: 'none',
  },
  getSendBtn: (isSending: boolean): React.CSSProperties => ({
    backgroundColor: '#2563eb',
    color: '#ffffff',
    border: 'none',
    padding: isMobile ? '0 14px' : '0 20px',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: isSending ? 'not-allowed' : 'pointer',
    opacity: isSending ? 0.7 : 1,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  }),
  concludedBox: {
    padding: '14px',
    textAlign: 'center' as const,
    backgroundColor: '#f1f5f9',
    color: '#64748b',
    fontSize: '13px',
  },

  /* LISTA DE MANIFESTAÇÕES */
  searchContainer: {
    position: 'relative' as const,
    marginBottom: '16px',
  },
  searchIcon: {
    position: 'absolute' as const,
    left: '12px',
    top: '12px',
    color: '#94a3b8',
  },
  searchInput: {
    width: '100%',
    padding: '10px 12px 10px 36px',
    borderRadius: '8px',
    border: '1px solid var(--border-color, #cbd5e1)',
    backgroundColor: 'var(--bg-main, #ffffff)',
    fontSize: '14px',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  loadingBox: {
    display: 'flex',
    justifyContent: 'center',
    padding: '40px',
    color: 'var(--text-secondary, #64748b)',
  },
  emptyListCard: {
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    padding: '40px 20px',
    textAlign: 'center' as const,
    color: 'var(--text-secondary, #64748b)',
  },
  emptyListTitle: {
    fontSize: '15px',
    fontWeight: 600,
    color: 'var(--text-secondary, #1e293b)',
  },
  emptyListSub: {
    fontSize: '13px',
    marginTop: '4px',
  },
  listContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  listItem: {
    backgroundColor: 'var(--bg-main, #ffffff)',
    borderRadius: '12px',
    border: '1px solid var(--border-color, #e2e8f0)',
    padding: isMobile ? '14px' : '16px 20px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    boxShadow: '0 1px 2px rgba(0,0,0,0.02)',
  },
  listItemMain: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    flex: 1,
    marginRight: '12px',
  },
  listItemHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexWrap: 'wrap' as const,
  },
  protocolBadge: {
    fontSize: '12px',
    fontWeight: 700,
    color: '#2563eb',
  },
  typeText: {
    fontSize: '12px',
    color: 'var(--text-secondary, #64748b)',
  },
  itemTitle: {
    fontSize: '15px',
    fontWeight: 600,
    color: 'var(--text-primary, #1e293b)',
  },
  itemMeta: {
    fontSize: '12px',
    color: '#94a3b8',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  itemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
});