name: Deploy Frontend Transparência

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Build e Push para o Registry (localhost)
        run: |
          docker build -t localhost:5000/transparencia:latest .
          docker push localhost:5000/transparencia:latest

      - name: Rodar a aplicação no servidor
        run: |
          docker rm -f site-transparencia || true
          
          docker run -d --name site-transparencia -p 3000:80 localhost:5000/transparencia:latest