name: Deploy Frontend Transparência

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Build e Push para o Registry
        run: |
          docker build -t localhost:5000/transparencia:latest .
          docker push localhost:5000/transparencia:latest

      - name: Atualizar Container da Aplicação
        run: |
          # Remove o container antigo se existir
          docker rm -f site-transparencia || true
          
          # Inicia a nova versão
          docker run -d \
            --name site-transparencia \
            -p 3000:80 \
            --restart=always \
            localhost:5000/transparencia:latest